<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="0.000">
  <properties />
            <testcase name="Atlas_Verification" time="0.000" classname="scripts.Atlas_Validation">
                <failure type="java.lang.RuntimeException"
                  message="org.apache.poi.openxml4j.exceptions.InvalidOperationException: Can&apos;t open the specified file: &apos;C:\Users\n.kumarasamy\Selenium\Selenium_CheckingMavenProject\src\test\java\resources\Selenium_DataSheet.xlsx&apos;"
              >
<![CDATA[java.lang.RuntimeException: org.apache.poi.openxml4j.exceptions.InvalidOperationException: Can't open the specified file: 'C:\Users\n.kumarasamy\Selenium\Selenium_CheckingMavenProject\src\test\java\resources\Selenium_DataSheet.xlsx'
  org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:143)
  org.testng.internal.Parameters.handleParameters(Parameters.java:426)
  org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
  org.testng.internal.Invoker.createParameters(Invoker.java:1075)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: org.apache.poi.openxml4j.exceptions.InvalidOperationException: Can't open the specified file: 'C:\Users\n.kumarasamy\Selenium\Selenium_CheckingMavenProject\src\test\java\resources\Selenium_DataSheet.xlsx'
  org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:102)
  org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:199)
  org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:178)
  org.apache.poi.POIXMLDocument.openPackage(POIXMLDocument.java:62)
  org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:188)
  driver.GenericMethods.getExcelData(GenericMethods.java:219)
  scripts.Atlas_Validation.getExcelData(Atlas_Validation.java:37)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:117)
  org.testng.internal.Parameters.handleParameters(Parameters.java:426)
  org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
  org.testng.internal.Invoker.createParameters(Invoker.java:1075)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
