<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BDC4A-L-529724B" name="scripts.Atlas_Validation" tests="1" failures="1" timestamp="30 Mar 2016 11:48:45 GMT" time="0.000" errors="0">
  <testcase name="Atlas_Verification" time="0.000" classname="scripts.Atlas_Validation">
    <failure type="java.lang.RuntimeException" message="org.apache.poi.openxml4j.exceptions.InvalidOperationException: Can&#039;t open the specified file: &#039;C:\Users\n.kumarasamy\Selenium\Selenium_CheckingMavenProject\src\test\java\resources\Selenium_DataSheet.xlsx&#039;">
      <![CDATA[java.lang.RuntimeException: org.apache.poi.openxml4j.exceptions.InvalidOperationException: Can't open the specified file: 'C:\Users\n.kumarasamy\Selenium\Selenium_CheckingMavenProject\src\test\java\resources\Selenium_DataSheet.xlsx'
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:143)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:426)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: org.apache.poi.openxml4j.exceptions.InvalidOperationException: Can't open the specified file: 'C:\Users\n.kumarasamy\Selenium\Selenium_CheckingMavenProject\src\test\java\resources\Selenium_DataSheet.xlsx'
	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:102)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:199)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:178)
	at org.apache.poi.POIXMLDocument.openPackage(POIXMLDocument.java:62)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:188)
	at driver.GenericMethods.getExcelData(GenericMethods.java:219)
	at scripts.Atlas_Validation.getExcelData(Atlas_Validation.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:117)
	... 20 more
]]>
    </failure>
  </testcase> <!-- Atlas_Verification -->
</testsuite> <!-- scripts.Atlas_Validation -->
